[lego] Optimize scripts

diff --git a/packages/lego/data/usr/bin/lego_wrapper b/packages/lego/data/usr/bin/lego_wrapper
--- a/packages/lego/data/usr/bin/lego_wrapper
+++ b/packages/lego/data/usr/bin/lego_wrapper
@@ -47,31 +47,21 @@ lego_run() {
 
 domain=""
 domains_file=""
-add_cron_jobs=0
-rm_cron_jobs=0
 
 print_usage() {
   echo "Usage: $(basename "$0") [option]..."
   echo "Options:"
   echo "  -n    Domain"
   echo "  -f    File contains domains"
-  echo "  -a    Add cron jobs"
-  echo "  -r    Remove cron jobs"
 }
 
-while getopts ':n:f:ar' OPTION; do
+while getopts ':n:f:' OPTION; do
   case "${OPTION}" in
   n)
     domain="${OPTARG}"
     ;;
   f)
     domains_file="${OPTARG}"
-    ;;
-  a)
-    add_cron_jobs=1
-    ;;
-  r)
-    rm_cron_jobs=1
     ;;
   ?)
     print_usage
@@ -80,25 +70,26 @@ while getopts ':n:f:ar' OPTION; do
   esac
 done
 
-if [ "${rm_cron_jobs}" = 1 ]; then
-  sed -i '/lego_wrapper/d' /etc/crontabs/root >/dev/null 2>&1
-  exit 0
-fi
-
 if [ -z "${domain}" ] && [ -z "${domains_file}" ]; then
   print_usage
   exit 1
 fi
 
+if [ -n "${domains_file}" ] && [ ! -f "${domains_file}" ]; then
+  print_usage
+  echo "File not found ${domains_file}"
+  exit 1
+fi
+
 if [ -z "${LEGO_EMAIL}" ]; then
   echo "LEGO_EMAIL is empty, please specify it in ${LEGO_PATH}/env"
+  exit 1
 fi
 
 [ ! -d "${LEGO_PATH}/hooks" ] && mkdir -p "${LEGO_PATH}/hooks"
 
 if [ -n "${domain}" ]; then
   lego_run "${domain}"
-  [ "${add_cron_jobs}" = 1 ] && echo "${LEGO_CRON_CONF} /usr/bin/lego_wrapper -n \"${domain}\" >>/var/log/lego.log 2>&1" >>/etc/crontabs/root
 fi
 
 if [ -n "${domains_file}" ]; then
@@ -106,5 +97,4 @@ if [ -n "${domains_file}" ]; then
     domain="$(echo "${domain}" | tr -d '\r')"
     lego_run "${domain}"
   done <"${domains_file}"
-  [ "${add_cron_jobs}" = 1 ] && echo "${LEGO_CRON_CONF} /usr/bin/lego_wrapper -f \"${domains_file}\" >>/var/log/lego.log 2>&1" >>/etc/crontabs/root
 fi
